site_name: Projekt LF8 - Angebotserstellung
nav:
 - "Startseite": index.md
 - "Aufgabenstellung": Aufgabenstellung.md
 - "Phase 1 - Übersicht": phase1.md
 - "Phase 1 - Anwendungsfalldiagramm": Anwendungsfalldiagramm.pdf
 - "Phase 3 - Sequenzdiagramm": Sequenzdiagramm.pdf
 - "Phase 5 - Daten": phase5.md
 - "Phase 6 - Nutzer": phase6.md
 - "Phase 7 - IT-Sicherheitskonzept": phase7.md
 - "Phase 8 - Datenmodell": phase8.md
 - "Phase 9 - Datenimplementierung": datenbank.sql
 - "Phase 10":
    - "Softwarelebenszyklus": softwarelebenszyklus.md
    - "Vorgehensmodelle": vorgehensmodelle.md
theme: material
