site_name: Projekt LF8 - Angebotserstellung
nav:
 - "Startseite": index.md
 - "Aufgabenstellung": Aufgabenstellung.md
 - "Phase 1 - Übersicht": phase1.md
 - "Phase 1 - Nutzfalldiagramm": Nutzfalldiagramm.pdf
 - "Phase 3 - Sequenzdiagramm": Sequenzdiagramm.pdf
 - "Phase 5 - Daten": phase5.md
theme: material
